Repository equinor/webviz-config, pull requests merged in 2021-11, with the labels that each got.

#539 Bugfix/radix oauth issues
  CHANGELOG.md
  CONTRIBUTING.md
  webviz_config/_localhost_token.py
  webviz_config/_oauth2.py
  webviz_config/templates/webviz_template.py.jinja2
Labels: next release 🚢

#550 Change to `AppData` wrt. Windows 11
  CHANGELOG.md
  webviz_config/_user_data_dir.py
Labels: bug 🐛, next release 🚢

#546 Cross platform `package.json`
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: next release 🚢

#553 Add `--flat` argument to `copyfiles`
  package.json
Labels: bug 🐛
