Repository equinor/webviz-config, pull requests merged in 2021-09, with the labels that each got.

#500 Add optional `pylint` option `useless-suppression`
  .pylintrc
  tests/test_plugin_init.py
  webviz_config/_config_parser.py
  webviz_config/_deployment/azure_cli.py
  webviz_config/_deployment/radix.py
  webviz_config/_docs/_build_docs.py
  webviz_config/_plugin_abc.py
  webviz_config/generic_plugins/_table_plotter.py
  webviz_config/plugins/_utils.py
  webviz_config/themes/__init__.py
  webviz_config/themes/_default_theme.py
Labels: maintenance

#498 When comparing timezones, explicitly use UTC.
  CHANGELOG.md
  webviz_config/_oauth2.py
Labels: next release 🚢

#502 Bump to `dash>=2.0`
  CHANGELOG.md
  CONTRIBUTING.md
  setup.py
  webviz_config/_plugin_abc.py
  webviz_config/generic_plugins/_banner_image.py
  webviz_config/generic_plugins/_data_table.py
  webviz_config/generic_plugins/_embed_pdf.py
  webviz_config/generic_plugins/_example_assets.py
  webviz_config/generic_plugins/_example_data_download.py
  webviz_config/generic_plugins/_example_plugin.py
  webviz_config/generic_plugins/_example_tour.py
  webviz_config/generic_plugins/_markdown.py
  webviz_config/generic_plugins/_syntax_highlighter.py
  webviz_config/generic_plugins/_table_plotter.py
  webviz_config/templates/webviz_template.py.jinja2
Labels: maintenance, next release 🚢

#476 Use `azure` `graph` + SDK directly
  CHANGELOG.md
  setup.py
  webviz_config/_deployment/azure_cli.py
  webviz_config/_deployment/azure_configuration.py
  webviz_config/_deployment/radix.py
Labels: maintenance, next release 🚢

#515 Add new + remove obsolete type hint `mypy` instructions
  mypy.ini
  webviz_config/__init__.py
  webviz_config/_config_parser.py
  webviz_config/_deployment/azure_cli.py
  webviz_config/_docs/_build_docs.py
  webviz_config/_localhost_token.py
  webviz_config/generic_plugins/_markdown.py
  webviz_config/plugins/__init__.py
  webviz_config/plugins/_utils.py
  webviz_config/themes/__init__.py
  webviz_config/utils/_localhost_open_browser.py
  webviz_config/utils/_silence_flask_startup.py
Labels: maintenance

#513 Fix undefined type annotation
  .github/workflows/webviz-config.yml
  webviz_config/_deployment/azure_cli.py
Labels: bug 🐛, next release 🚢

#496 Implemented automatic menu creation from YAML file
  CHANGELOG.md
  examples/basic_example.yaml
  examples/basic_example_advanced_menu.yaml
  tests/conftest.py
  tests/test_portable.py
  tests/test_schema.py
  webviz_config/_config_parser.py
  webviz_config/_docs/_create_schema.py
  webviz_config/templates/copy_data_template.py.jinja2
  webviz_config/templates/webviz_template.py.jinja2
  webviz_config/themes/_default_theme.py
  webviz_config/themes/default_assets/default_logo.svg
  webviz_config/themes/default_assets/default_theme.css
Labels: enhancement 🚀, next release 🚢

#521 Improve `git` steps of deployment
  CHANGELOG.md
  webviz_config/_deployment/github_cli.py
  webviz_config/_deployment/radix.py
Labels: next release 🚢
