Repository equinor/webviz-config, pull requests merged in 2022-11, with the labels that each got.

#644 Added table download to `DataTable` and `PivotTable`
  CHANGELOG.md
  tests/test_data_table.py
  webviz_config/generic_plugins/_data_table.py
  webviz_config/generic_plugins/_pivot_table.py
Labels: enhancement 🚀

#648 Allow `blob:` in `script-src` CSP
  CHANGELOG.md
  webviz_config/_theme_class.py
Labels: next release 🚢

#652 Enable MathJax in `dcc.Markdown`
  CHANGELOG.md
  examples/basic_example.yaml
  examples/example-markdown.md
  webviz_config/generic_plugins/_markdown.py
  webviz_config/templates/webviz_template.py.jinja2
Labels: enhancement 🚀, next release 🚢

#653 Lazy load modules in command line entrypoint
  CHANGELOG.md
  webviz_config/command_line.py
Labels: enhancement 🚀

#655 Regression fix: Show filters in TablePlotter when using `lock`
  CHANGELOG.md
  examples/basic_example.yaml
  tests/test_table_plotter.py
  webviz_config/generic_plugins/_table_plotter.py
Labels: bug 🐛, next release 🚢
