Repository equinor/webviz-config, pull requests merged in 2022-09, with the labels that each got.

#626 Improved `callback_typecheck` decorator, moved it and added test
  tests/test_callback_typecheck.py
  webviz_config/generic_plugins/_example_wlf_plugin/_shared_settings/_shared_settings.py
  webviz_config/generic_plugins/_example_wlf_plugin/_views/_plot/_view.py
  webviz_config/generic_plugins/_example_wlf_plugin/_views/_table/_view.py
  webviz_config/utils/__init__.py
  webviz_config/utils/_callback_typecheck.py
  webviz_config/webviz_plugin_subclasses/__init__.py
Labels: enhancement 🚀

#627 Added try except statement around `isinstance` check to avoid exception
  tests/test_callback_typecheck.py
  webviz_config/utils/_callback_typecheck.py
Labels: bug 🐛

#629 Add line color as view element setting for Plot in WLF example plugin
  webviz_config/generic_plugins/_example_wlf_plugin/_plugin.py
  webviz_config/generic_plugins/_example_wlf_plugin/_views/_plot/__init__.py
  webviz_config/generic_plugins/_example_wlf_plugin/_views/_plot/_view.py
Labels: enhancement 🚀

#631 Implemented new `homepage` option in `menu > options` in config file
  CHANGELOG.md
  webviz_config/_config_parser.py
  webviz_config/_docs/_create_schema.py
  webviz_config/templates/webviz_template.py.jinja2
Labels: enhancement 🚀, next release 🚢

#632 Improved typechecking, especially for `Union`
  tests/test_callback_typecheck.py
  webviz_config/utils/_callback_typecheck.py
Labels: bug 🐛, enhancement 🚀, next release 🚢

#635 Add interactive option to lock axis ranges in `Tableplotter`
  CHANGELOG.md
  examples/basic_example.yaml
  webviz_config/generic_plugins/_table_plotter.py
Labels: enhancement 🚀, next release 🚢

#543 Improved image spacing
  CHANGELOG.md
  webviz_config/static/assets/webviz_config.css
Labels: next release 🚢
